### PR TITLE
Local setup update

### PR DESCRIPTION
**Pull request by StarTrooper08**
Changes made
- Now contributor can create files inside devcontainer localsetup and also use the helper scripts(which_r and set_build_r) inside local setup devcontainer.

PR for issue number : #157

### CODE REVIEW

**Comment by iaine** [comment]
I can create a new folder and files when I build the Docker container. However, I cannot use which_r and set_build_r:
Screenshot 2024-08-16 at 09 59 34
It might be that the scripts are not executable in the scripts folder. Need to add chmod+x when assigning to the vscode user?

**Comment by iaine** [comment]
When I rebuild the container on my Mac, I get:
Screenshot 2024-08-16 at 10 28 35
This is causing issues with which_r and set_build_r scripts.

**Comment by StarTrooper08** [comment]
image
Its working on my device!?

**Comment by StarTrooper08** [comment]
image

**Comment by iaine** [comment]
Hmm, may be a Mac issue as the container is running through emulation (see #112

**Comment by StarTrooper08** [comment]
Yes I tried building image for mac OS. But failed to build ARM based image for R dev container.
https://github.com/StarTrooper08/r-dev-env/actions/runs/10406051407/job/28818214756

**Comment by StarTrooper08** [comment]
Right now not why I'm unable to build cross platform docker image using docker buildx

**Comment by iaine** [comment]
I’ll open this as a new issue. The PR solves the initial use raised by @eliocamp .

On 16 Aug 2024, at 11:04, Atharva Shirdhankar ***@***.***> wrote:



Right now not why I'm unable to build cross platform docker image using docker buildx

**Pull request merged**
